# Import Numpy as np

In [2]:
import numpy as np

create an array of 10 zeros

In [4]:
arr0 = np.zeros(10)
arr0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

create an array of 10 ones

In [5]:
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

create an array of 10 fives

In [7]:
arr5 = arr1 * 5
arr5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

create an array of integers from 0 to 50 

In [8]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

creat an array of even integers from 0 to 50 

In [9]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

create a 3x3 matrix with values ranging from 0 to 8 (2 steps)

In [10]:
arrq7 = np.arange(0,9)

In [11]:
arrq7.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

create a random number between 0 and 1

In [13]:
np.random.rand(1)

array([0.87412677])

create a 5x5 matrix of numbers ranging from 0 to 25

In [15]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

sum of numbers in the above matrix

In [17]:
np.sum(mat)

325

standard deviation of matrix above

In [18]:
np.std(mat)

7.211102550927978

create matrix to add and multiply to original matrix

In [21]:
mat1 = np.ones(25).reshape(5,5)
mat1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

add the two matricies

In [22]:
mat + mat1

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21.],
       [22., 23., 24., 25., 26.]])

Multiply the two matricies

In [23]:
mat * mat1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

# DONE